version: "3.9"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/:/root/data
    environment:
      - REDIS_PASSWORD=${RD_PASSWORD}
      - REDIS_PORT=${RD_PORT}
      - REDIS_DATABASE=16
